[project]
name = "system-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Azokyen", email = "260447539+svrosa@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.2.2",
    "textual>=8.2.8",
]

[project.scripts]
sysmon = "system_monitor:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
